### ISSUE TITLE
Implement all instructions

### ISSUE THREAD

**Issue by xtuc** [xtuc/js-webassembly-interpreter#1]
- [x] `unreachable`
- [x] `nop`
- [x] `block`
- [ ] `loop`
- [x] `if`
- [x] `else`
- [x] `end`
- [ ] `br`
- [ ] `br_if`
- [ ] `brtable`
- [ ] `return`
- [x] `call`
- [ ] `callindirect`
- [x] `drop`
- [ ] `select`
- [x] `getlocal`
- [x] `setlocal`
- [ ] `teelocal`
- [ ] `getglobal`
- [ ] `setglobal`
- [ ] `i32.load`
- [ ] `i64.load`
- [ ] `f32.load`
- [ ] `f64.load`
- [ ] `i32.load8_s`
- [ ] `i32.load8_u`
- [ ] `i32.load16_s`
- [ ] `i32.load16_u`
- [ ] `i64.load8_s`
- [ ] `i64.load8_u`
- [ ] `i64.load16_s`
- [ ] `i64.load16_u`
- [ ] `i64.load32_s`
- [ ] `i64.load32_u`
- [ ] `i32.store`
- [ ] `i64.store`
- [ ] `f32.store`
- [ ] `f64.store`
- [ ] `i32.store8`
- [ ] `i32.store16`
- [ ] `i64.store8`
- [ ] `i64.store16`
- [ ] `i64.store32`
- [ ] `currentmemory`
- [ ] `growmemory`
- [x] `i32.const`
- [x] `i64.const`
- [x] `f32.const`
- [x] `f64.const`
- [ ] `i32.eqz`
- [ ] `i32.eq`
- [ ] `i32.ne`
- [ ] `i32.lt_s`
- [ ] `i32.lt_u`
- [ ] `i32.gt_s`
- [ ] `i32.gt_u`
- [ ] `i32.le_s`
- [ ] `i32.le_u`
- [ ] `i32.ge_s`
- [ ] `i32.ge_u`
- [ ] `i64.eqz`
- [ ] `i64.eq`
- [ ] `i64.ne`
- [ ] `i64.lt_s`
- [ ] `i64.lt_u`
- [ ] `i64.gt_s`
- [ ] `i64.gt_u`
- [ ] `i64.le_s`
- [ ] `i64.le_u`
- [ ] `i64.ge_s`
- [ ] `i64.ge_u`
- [ ] `f32.eq`
- [ ] `f32.ne`
- [ ] `f32.lt`
- [ ] `f32.gt`
- [ ] `f32.le`
- [ ] `f32.ge`
- [ ] `f64.eq`
- [ ] `f64.ne`
- [ ] `f64.lt`
- [ ] `f64.gt`
- [ ] `f64.le`
- [ ] `f64.ge`
- [ ] `i32.clz`
- [ ] `i32.ctz`
- [ ] `i32.popcnt`
- [x] `i32.add`
- [x] `i32.sub`
- [x] `i32.mul`
- [x] `i32.div_s`
- [x] `i32.div_u`
- [ ] `i32.rem_s`
- [ ] `i32.rem_u`
- [ ] `i32.and`
- [ ] `i32.or`
- [x] `i32.xor`
- [ ] `i32.shl`
- [ ] `i32.shr_s`
- [ ] `i32.shr_u`
- [ ] `i32.rotl`
- [ ] `i32.rotr`
- [ ] `i64.clz`
- [ ] `i64.ctz`
- [ ] `i64.popcnt`
- [x] `i64.add`
- [x] `i64.sub`
- [x] `i64.mul`
- [x] `i64.div_s`
- [x] `i64.div_u`
- [ ] `i64.rem_s`
- [ ] `i64.rem_u`
- [ ] `i64.and`
- [ ] `i64.or`
- [ ] `i64.xor`
- [ ] `i64.shl`
- [ ] `i64.shr_s`
- [ ] `i64.shr_u`
- [ ] `i64.rotl`
- [ ] `i64.rotr`
- [x] `f32.abs`
- [ ] `f32.neg`
- [ ] `f32.ceil`
- [ ] `f32.floor`
- [ ] `f32.trunc`
- [ ] `f32.nearest`
- [ ] `f32.sqrt`
- [x] `f32.add`
- [x] `f32.sub`
- [x] `f32.mul`
- [x] `f32.div`
- [x] `f32.fmin`
- [x] `f32.fmax`
- [x] `f32.copysign`
- [ ] `f64.abs`
- [ ] `f64.neg`
- [ ] `f64.ceil`
- [ ] `f64.floor`
- [ ] `f64.trunc`
- [ ] `f64.nearest`
- [ ] `f64.sqrt`
- [x] `f64.add`
- [x] `f64.sub`
- [x] `f64.mul`
- [x] `f64.div`
- [x] `f64.fmin`
- [x] `f64.fmax`
- [x] `f64.copysign`
- [ ] `i32.wrap`
- [ ] `i32.trunc_s`
- [ ] `i32.trunc_u`
- [ ] `i32.trunc_s`
- [ ] `i32.trunc_u`
- [ ] `i64.extend_s`
- [ ] `i64.extend_u`
- [ ] `i64.trunc_s`
- [ ] `i64.trunc_u`
- [ ] `i64.trunc_s`
- [ ] `i64.trunc_u`
- [ ] `f32.convert_s`
- [ ] `f32.convert_u`
- [ ] `f32.convert_s`
- [ ] `f32.convert_u`
- [ ] `f32.demote`
- [ ] `f64.convert_s`
- [ ] `f64.convert_u`
- [ ] `f64.convert_s`
- [ ] `f64.convert_u`
- [ ] `f64.promote`
- [ ] `i32.reinterpret`
- [ ] `i64.reinterpret`
- [ ] `f32.reinterpret`
- [ ] `f64.reinterpret`

**Comment by maurobringolf** [comment]
(For coordination) I plan to work on these tomorrow:

* f32.copysign
* f64.abs
* f64.neg
* f64.ceil
* f64.floor
* f64.trunc
* f64.nearest
* f64.sqrt

**Comment by xtuc** [comment]
To allow more future contributions and to be able to better keep track of implementations I would like to split this into separated issues (one for each instruction or group of instructions). What do you think?

**Comment by maurobringolf** [comment]
Thats a good idea, contributing will become easier and more rewarding when one PR can close on issue.

**Comment by xtuc** [comment]
agreed, I'm closing this and will open a few issues.
