### ISSUE TITLE
the wast parser should fail if the named offset argument is negative

### ISSUE THREAD

**Issue by ColinEberhardt** [xtuc/js-webassembly-interpreter#126]
The wat2wasm tool fails when faced with the following command:

`i32.store offset=-1`

With the following error:

`error: unexpected token offset=-1, expected )`

Currently our implementation allows negative values for named arguments.

**Comment by xtuc** [comment]
Yes, that a good point. It's the case for every `Index` (https://webassembly.github.io/spec/core/syntax/modules.html#indices).

For example `(get_global -1)` can't now work (currently does here).

**Comment by xtuc** [comment]
FYI @johnsudaar is working on it.

I mentioned that every Index is an u32, unfortunately it's way more complicated that just handling the named argument case. 

We need to get the opcode map first to determine what is expected after `get_local x`.

**Comment by ColinEberhardt** [comment]
> it's way more complicated that just handling the named argument case

perhaps not a `good first issue` then? 😉

**Comment by xtuc** [comment]
First time contributors can just ignore my comment.

In the case of named argument we just need an assertion here:
https://github.com/xtuc/js-webassembly-interpreter/blob/master/src/compiler/parsing/watf/grammar.js#L732-L736

which is a `good first issue`.
