### ISSUE TITLE
WATF?

### ISSUE THREAD

**Issue by binji** [xtuc/js-webassembly-interpreter#151]
I'm curious as to why WATF is used, as it seems this project is the only one using this term. The WebAssembly text format is called `.wat` everywhere else.

**Comment by xtuc** [comment]
That's a good question, I can't remember why I preferred `watf` over `wat`. Wasn't it its initial name?

Should we probably rename it? Since it's official in the spec.

**Comment by xtuc** [comment]
I'll do it, https://github.com/xtuc/js-webassembly-interpreter/issues/152. Thanks.
