### ISSUE TITLE
Remove the VM/sandbox in benchmarks

### ISSUE THREAD

**Issue by xtuc** [xtuc/js-webassembly-interpreter#39]
Following https://github.com/nodejs/node/issues/17884

Running the benchmark in a sandbox decreases the performance and leads to incorrect results.

**Comment by apapirovski** [comment]
Btw I think the `benchmark/add/` folder is also missing the `wasm` file, unless I'm missing something. I had to download the one you linked in the Node.js issue.

**Comment by xtuc** [comment]
Once again you're correct. Wasm binaries are ignored by git (.gitignore).

I'll add it, thanks.

**Comment by xtuc** [comment]
Note from Twitter:

> Oh, but: Accessing global variables a lot might be more expensive!
`NBINTERATION` in the test script would currently always be fetched from the global (on each iteration), and that's where the sandbox comes into play and slows things down.

**Comment by xtuc** [comment]
Optimizing the benchmark : https://github.com/nodejs/node/issues/17884#issuecomment-354239027
