### ISSUE TITLE
Correct WATF grammar

### ISSUE THREAD

**Issue by xtuc** [xtuc/js-webassembly-interpreter#47]
[Example](https://github.com/xtuc/js-webassembly-interpreter/blob/master/test/compiler/parsing/fixtures/watf/call/actual.wast#L2):

```wast
  (func (
    (call 1)
  ))
```

Should be 

```wast
  (func
    (call 1)
  )
```

WAST definition:

```
func:    ( func <name>? <func_sig> <local>* <instr>* )
instr:
  <expr>
  <op>                                                              ;; = (<op>)
  block <name>? <block_sig> <instr>* end <name>?                    ;; = (block <name>? <block_sig> <instr>*)
  loop <name>? <block_sig> <instr>* end <name>?                     ;; = (loop <name>? <block_sig> <instr>*)
  if <name>? <block_sig> <instr>* end <name>?                       ;; = (if <name>? <block_sig> (then <instr>*))
  if <name>? <block_sig> <instr>* else <name>? <instr>* end <name>? ;; = (if <name>? <block_sig> (then <instr>*) (else <instr>*))

op:
  unreachable
  nop
  br <var>
...
```

And WATF definitions is [here](https://webassembly.github.io/spec/core/text/modules.html#functions)

**Comment by maurobringolf** [comment]
Do I understand this correctly: The syntax with extra parentheses is not allowed in WAST and WATF, but our grammar currently allows it?

```wasm
(func (
  (call 1)
))
```

**Comment by xtuc** [comment]
Our grammar ensures it and that's wrong. I'll post a few examples in a moment.

**Comment by xtuc** [comment]
## Clean WAST from WebAssembly explorator

```wast
(module
  (type $type0 (func (result i32)))
  (table 0 anyfunc)
  (memory 1)
  (export "memory" memory)
  (export "main" $func0)
  (func $func0 (result i32)
    i32.const 0
    i32.load offset=4
    i32.const 16
    i32.sub
    i32.const 0
    i32.store offset=12
    i32.const 1
  )
)
```

Instructions are not surrounded by parens and we can split them by line (currently already done-ish).

### One liner

From the spec tests (so WAST).

```wast
(func (export "type-i64") (result i32) (unreachable))
```

## WAST

```wast
(func $f)
(func)
(func (export "type-f64-value") (result f64)
  (block (result f64) (f64.neg (br_table 0 0 (f64.const 4) (i32.const 0))))
)
```

---

This is the case for every block instructions: if, loop, block, ...

**Comment by xtuc** [comment]
This will be my next focus because that will allow us to use the spec tests: https://github.com/WebAssembly/spec/tree/master/test/core

**Comment by maurobringolf** [comment]
Okay then I'll focus on supporting all number literals as in #32 and #46 to support the numeric test cases.
