### ISSUE TITLE
Implement memory operation instructions

### ISSUE THREAD

**Issue by xtuc** [xtuc/js-webassembly-interpreter#59]
Load:
- [x] `i32.load`
- [x] `i64.load`
- [x] `f32.load`
- [x] `f64.load`
- [x] `i32.load8_s`
- [x] `i32.load8_u`
- [x] `i32.load16_s`
- [x] `i32.load16_u`
- [x] `i64.load8_s`
- [x] `i64.load8_u`
- [x] `i64.load16_s`
- [x] `i64.load16_u`
- [x] `i64.load32_s`
- [x] `i64.load32_u`

Store:
- [x] `i32.store`
- [x] `i64.store`
- [x] `f32.store`
- [x] `f64.store`
- [x] `i32.store8`
- [x] `i32.store16`
- [x] `i64.store8`
- [x] `i64.store16`
- [x] `i64.store32`

See specification here https://webassembly.github.io/spec/core/exec/instructions.html#exec-load.

This depends on https://github.com/xtuc/js-webassembly-interpreter/issues/29

**Comment by ColinEberhardt** [comment]
I have a question about how this might be implemented. With the current code you can supply a `Memory` instance via the module imports:

https://github.com/xtuc/js-webassembly-interpreter/blob/master/src/interpreter/index.js#L59

However, this seems to be used as the 'allocator' which the `ModuleInstance` uses at runtime to store things like functions and globals.

My understanding is that WebAssembly linear memory is separate from the runtime stack, so I wouldn't expect runtime related information to appear in the `Memory` I supply to my WebAssembly  module.

Have I correctly understood the current implementation?

**Comment by xtuc** [comment]
Now that i'm thinking about it there might be a misunderstand on my side.

Currently, you can either provide an WebAssembly.Memory (at instantiation) or a default one will be created, they are both used as backend of the allocator and available at runtime for memory allocations.

**Comment by xtuc** [comment]
:tada:
