### ISSUE TITLE
Implement binary instructions

### ISSUE THREAD

**Issue by xtuc** [xtuc/js-webassembly-interpreter#65]
- [ ] `i32.clz`
- [ ] `i32.ctz`
- [ ] `i32.popcnt`
- [ ] `i32.rem_s`
- [ ] `i32.rem_u`
- [ ] `i32.and`
- [ ] `i32.or`
- [ ] `i32.shl`
- [ ] `i32.shr_s`
- [ ] `i32.shr_u`
- [ ] `i32.rotl`
- [ ] `i32.rotr`
- [ ] `i64.clz`
- [ ] `i64.ctz`
- [ ] `i64.popcnt`
- [ ] `i64.rem_s`
- [ ] `i64.rem_u`
- [ ] `i64.and`
- [ ] `i64.or`
- [ ] `i64.shl`
- [ ] `i64.shr_s`
- [ ] `i64.shr_u`
- [ ] `i64.rotl`
- [ ] `i64.rotr`

See specification here: https://webassembly.github.io/spec/core/exec/numerics.html#op-ictz

**Comment by ColinEberhardt** [comment]
this is a dup of #97
