### ISSUE TITLE
binary operations are the wrong way round?

### ISSUE THREAD

**Issue by ColinEberhardt** [xtuc/js-webassembly-interpreter#86]
From the tests:

https://github.com/xtuc/js-webassembly-interpreter/blob/master/test/interpreter/kernel/exec/numeric-instructions.js#L217

```
    {
      name: "f32.div",

      args: [{ value: 2.0, type: "f32" }, { value: 10.0, type: "f32" }],

      code: [
        t.instruction("get_local", [t.numberLiteral(0)]),
        t.instruction("get_local", [t.numberLiteral(1)]),
        t.objectInstruction("div", "f32")
      ],

      resEqual: 5.0
    },
```

My reading is that this is equivalent to:

```
(module
  (func $test (param f32) (param f32) (result f32)
   (get_local 0)
   (get_local 1)
   (f32.div)
  )
  (export "test" (func $test))
)
```

```
instance.exports.test(2, 10)
```

Which gives `0.2`

i.e. it looks like the arguments to the binary operations are the wrong way round.

**Comment by xtuc** [comment]
From the spec:

2. Pop the value t.const c2 from the stack.
3. Pop the value t.const c1 from the stack.
4. `binopt(c1,c2)`

Here an example in WAST:
```wat
(module
  (func $test (param $l f32) (param $r f32) (result f32)
   (get_local $l)
   (get_local $r)

   ;; Stack is ($l, $r)
   ;; c2 = $r
   ;; c1 = $l
   (f32.div)
  )
  (export "test" (func $test))
)
```

This will be `f32.div ( $l, $r )`.

Does it make sense to you?

**Comment by ColinEberhardt** [comment]
Yes, I agree. And just to be sure, I created a new integration test within `test/interpreter/fixtures` with the following code:

```
(module
  (func $test (param f32) (param f32) (result f32)
   (get_local 0)
   (get_local 1)
   (f32.div)
  )
  (export "test" (func $test))
)
```

Which demonstrates that the current implementation has reports the wrong result due to flipping the operands.

**Comment by xtuc** [comment]
Yes, thanks. That's a good catch! 

Note that we would have caught that with #76, I will try to get that done asap.
