### ISSUE TITLE
incorrect implementation of i32.div_s

### ISSUE THREAD

**Issue by ColinEberhardt** [xtuc/js-webassembly-interpreter#87]
The current implementation treats `div_s` and `div_u` as the same operation. However, as per the specification, `div_s` uses a 'signed' interpretation of the values:

https://webassembly.github.io/spec/core/exec/numerics.html#aux-signed

this has an impact for numbers where the most significant bit is '1'. 

To illustrate:

**unsigned**

```
(module
  (func $test (param i32) (param i32) (result i32)
   (get_local 0)
   (get_local 1)
   (i32.div_u)
  )
  (export "test" (func $test))
)
```
```
instance.exports.test(0xffffff00, 0x2);
```
```
2147483520
```

**signed**

```
(module
  (func $test (param i32) (param i32) (result i32)
   (get_local 0)
   (get_local 1)
   (i32.div_s)
  )
  (export "test" (func $test))
)
```
```
instance.exports.test(0xffffff00, 0x2);
```
```
-128
```

**Comment by maurobringolf** [comment]
I was confused when I first read the code as well. I also expected the interpreter to make a distinction. Don't have time to dig in further right now though.

**Comment by ColinEberhardt** [comment]
No worries. Rather than move onto reinterpret, I'll look to fix some of these bugs first.

From a general design perspective, there are a number of areas where we are going to have to apply some additional logic on top of the numeric operations that JavaScript provides. For example:

 - Handing NaN as per #46 
 - Handling i64 values
 - Handling signed / unsigned operations

We'll likely uncover more.

In the same way that we support i64 via long.js, I wonder whether it's worth adding similar types that 'boxes' all of our numeric types at runtime? i.e.

Create an interface, similar to long.js ...

```
interface Number {
  multiply(number: value): Number;
  add(number: value): Number;
  ... other binary operations
}
```

Then create x4 implementations of the above interface, one for each of the numeric types?

**Comment by maurobringolf** [comment]
I like this idea. I think the main goal by using as much JS standard library and raw numbers as possible is performance? I am not sure how much impact boxing all values in objects would have on that.

From a conceptual standpoint the interface makes a lot of sense to me.

**Comment by xtuc** [comment]
It's always difficult to tell with the JIT, but I assume the performance impact of "everything is an object" is insignificant compared to the gain of maintainability .
